### ISSUE TITLE
Please add README.md so others know how to use this potentially amazing plugin

### ISSUE THREAD

**Issue by moshpirit** [semycolon/vlc-skip-silence#1]

**Comment by asheghi** [comment]
honestly didn't expect this to be "potentially amazing plugin", but sure, I'll modify the code and write a README asap.

**Comment by moshpirit** [comment]
hi, I don't want to hurry or anything but a month passed since we spoke :sweat_smile:

**Comment by asheghi** [comment]
fair enough!

**Comment by moshpirit** [comment]
Thanks! BTW, when you say "install it globally", do you mean, like an extension or does it mean that by default VLC is going to skip silences by default?

**Comment by asheghi** [comment]
it'a about Node.js Package Manager(NPM), not vlc.
you can read more about NPM in this [link](https://www.geeksforgeeks.org/what-are-the-differences-between-npm-and-npx/#:~:text=Npm%20is%20a%20tool%20that,pollution%20for%20the%20long%20term.)
